---
project:
  type: website
    
website:
  open-graph: true
  title: "Quarto NHS Theme"
  description: "NHS Theme"
  site-url: https://nhs-r-community.github.io/quarto-nhs-theme
  favicon: docs/_assets/favicon.ico
  repo-url: https://github.com/nhs-r-community/quarto-nhs-theme
  repo-actions: [edit, issue]

  page-footer:
    left: "This page is built [Quarto](https://quarto.org/)."
    right:
    - text: "License"
      href: https://github.com/nhs-r-community/quarto-nhs-theme/blob/main/LICENCE
    - text: "Code of Conduct"
      href: https://github.com/nhs-r-community/quarto-nhs-theme/blob/main/CODE_OF_CONDUCT.md

  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "quarto-nhs-theme"
        icon: "box-seam"
        href: index.qmd
      - text: "Tutorials"
        icon: "bookmark-check"
        href: tutorials/index.qmd
      - text: "Documentation"
        icon: "file-earmark-text"
        href: documentation/index.qmd
      - text: "Updates"
        icon: "rss"
        href: updates.qmd
    right:
      - text: "Help"
        menu:
          - text: "About"
            icon: "info-circle"
            href: about.qmd
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/nhs-r-community/quarto-nhs-theme/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/nhs-r-community/quarto-nhs-theme/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: faq.qmd
      - icon: github
        href: https://github.com/nhs-r-community/
        aria-label: GitHub
      - icon: cloud-fill
        href: https://nhsrcommunity.com/
        aria-label: NHS-R Community
  sidebar:
    id: toc-side
    style: "floating"
    pinned: true
    contents:
      - text: "Homepage" 
        file: index.qmd
      - text: "Contribute to docs"
        file: contribute.qmd
      - section: Tutorials
        file: tutorials/index.qmd
        contents: 
          - auto: tutorials/*.qmd
      - section: Documentation
        file: documentation/index.qmd
        contents: 
          - auto: documentation/*.qmd
      - text: "FAQ"
        file: faq.qmd
      - text: "About"
        file: about.qmd
  comments:
    giscus:
      repo: nhs-r-community/quarto-nhs-theme
format:
  html:
    toc: true
    toc-depth: 4
    theme:
      light: [cosmo, _assets/style/theme.scss]
    code-copy: true
    code-overflow: wrap
    css: _assets/style/styles.css
    include-after-body: _assets/style/js.html
    
warning: false

execute:
  freeze: auto
---

## % FIT10 data

Percentage of colonoscopies with a FIT10+ result

```{r}
#| echo: false

library(dplyr)
library(kableExtra)

source("C:/Users/martin.bloyce/OneDrive - NHS England/Documents/diagnostics_endoscopy/endoscopy_fit.R")

gradient_colour <- function(x) {
  colorRampPalette(c("red", "yellow", "green"))(100)[as.integer((x - min(x)) / (max(x) - min(x)) *99) +1]
}

#master$percent_of_baseline_colour <- sapply(master$percent_of_baseline, gradient_colour)

# Remove colour column
#master <- master[, -which(names(master) == "percent_of_baseline_colour")]

# Calculate totals
#total_row <- colSums(master[, sapply(master, is.numeric)])
#total_row[1] <- "Total"  # Label first element as "Total"

# Convert totals to a data frame row
#total_row_df <- as.data.frame(t(total_row))
#total_row_df[, 'orgshortname'] <- "Total"
#total_row_df <- total_row_df %>% select(c("Loc", "Baseline", "Activity", "percent_of_baseline"))

# Add total row to bottom of master table
#master <- rbind(master, total_row_df)

kable(fit_table,
             col.names = colnames(fit_table),
             caption = "Sample Table") %>%
               kable_styling(full_width = FALSE) %>%
                add_header_above(c(" ", "Percentage of colonoscopies with a FIT10+ result" = 8)) %>%
               row_spec(0, bold = TRUE, color = "white", background = "gray") %>%
               column_spec(9, color = "white",
              background = spec_color(fit_table$percentageFit10[1:12], begin = 0.9, end = 0.4, option = 'H'))

a

b

```

## Endoscopy activity

DM01 activity used, for gastroscopies and colonoscopies only.

```{r}
#| echo: false

library(dplyr)
library(kableExtra)

source("C:/Users/martin.bloyce/OneDrive - NHS England/Documents/diagnostics_endoscopy/endoscopy_activity.R")

gradient_colour <- function(x) {
  colorRampPalette(c("red", "yellow", "green"))(100)[as.integer((x - min(x)) / (max(x) - min(x)) *99) +1]
}

#master$percent_of_baseline_colour <- sapply(master$percent_of_baseline, gradient_colour)

# Remove colour column
#master <- master[, -which(names(master) == "percent_of_baseline_colour")]

# Calculate totals
#total_row <- colSums(master[, sapply(master, is.numeric)])
#total_row[1] <- "Total"  # Label first element as "Total"

# Convert totals to a data frame row
#total_row_df <- as.data.frame(t(total_row))
#total_row_df[, 'orgshortname'] <- "Total"
#total_row_df <- total_row_df %>% select(c("Loc", "Baseline", "Activity", "percent_of_baseline"))

# Add total row to bottom of master table
#master <- rbind(master, total_row_df)

kable(master,
             col.names = colnames(master),
             caption = "Sample Table") %>%
               kable_styling(full_width = FALSE) %>%
                add_header_above(c(" ", "DM01 diagnostic activity (gastroscopies and colonoscopies only)" = 3)) %>%
               row_spec(0, bold = TRUE, color = "white", background = "gray") %>%
               column_spec(4, color = "black",
                background = ifelse(master$percent_of_baseline >= 100, "green", ifelse(master$percent_of_baseline > 90, "yellow", "red")))


```

## Future demand

Lists per week used for current position, with following models used for future demand predictions: - 120% activity - Current demand, plus 5% uplift for each subsequent year (as specified in the Richards' Review)

```{r}
#| echo: false

library(dplyr)
library(kableExtra)

source("C:/Users/martin.bloyce/OneDrive - NHS England/Documents/diagnostics_endoscopy/future_demand_modelling.R")

gradient_colour <- function(x) {
  colorRampPalette(c("red", "yellow", "green"))(100)[as.integer((x - min(x)) / (max(x) - min(x)) *99) +1]
}

#master$percent_of_baseline_colour <- sapply(master$percent_of_baseline, gradient_colour)

# Remove colour column
#master <- master[, -which(names(master) == "percent_of_baseline_colour")]

# Calculate totals
#total_row <- colSums(master[, sapply(master, is.numeric)])
#total_row[1] <- "Total"  # Label first element as "Total"

# Convert totals to a data frame row
#total_row_df <- as.data.frame(t(total_row))
#total_row_df[, 'orgshortname'] <- "Total"
#total_row_df <- total_row_df %>% select(c("Loc", "Baseline", "Activity", "percent_of_baseline"))

# Add total row to bottom of master table
#master <- rbind(master, total_row_df)

kable(lists_per_week,
             col.names = colnames(lists_per_week),
             caption = "Sample Table") %>%
               kable_styling(full_width = FALSE) %>%
                add_header_above(c(" ", "Lists per week" = 6)) %>%
               row_spec(0, bold = TRUE, color = "white", background = "gray") %>%
               column_spec(4, background = lists_per_week$gradient_colour)

```
